### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by zenified** [RobotWebTools/webrtc_ros#32]
Hi I was met with the following error when building the package

> No rule to make target `/home/rrc/catkin/devel/lib/libwebrtc_jsoncpp.a', needed by `/home/rrc/catkin/devel/lib/libwebrtc_ros_server.so'.  Stop.

Did I missed something required ?

**Comment by hankewei** [comment]
I also met this problem. How do you solve it? Thank you.
